name: neumorphic_phone_dialer
description: Neomorphic phone_dialer app.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  equatable: 2.0.5
  flutter_svg: 1.1.5
  http:
  auto_route: 5.0.1
  flutter_bloc: 8.1.1
  flutter_phone_direct_caller: 2.1.1
  flutter_neumorphic: 3.2.0
  flutter_multi_formatter: 2.7.4
  contacts_service: 0.6.3
  cupertino_icons: ^1.0.2
  permission_handler: 10.2.0
  string_to_hex: 0.2.2
  get_it: 7.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  auto_route_generator: ^5.0.2
  build_runner: ^2.2.1
  ferry_generator: ^0.6.0
  freezed: ^2.1.0+1
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
